### Variables

In [1]:
x = 5

In [2]:
x

5

In [3]:
x + 2

7

In [4]:
x - 2

3

In [5]:
x*2

10

In [6]:
x**2

25

In [7]:
x / 2

2.5

In [8]:
x % 2

1

### Type Conversions

In [9]:
type(x)

int

In [10]:
str(x)

'5'

In [11]:
int(x)

5

In [12]:
float(x)

5.0

In [13]:
bool(x)

True

In [14]:
help(str)

Help on class str in module builtins:

class str(object)
 |  str(object='') -> str
 |  str(bytes_or_buffer[, encoding[, errors]]) -> str
 |  
 |  Create a new string object from the given object. If encoding or
 |  errors is specified, then the object must expose a data buffer
 |  that will be decoded using the given encoding and error handler.
 |  Otherwise, returns the result of object.__str__() (if defined)
 |  or repr(object).
 |  encoding defaults to sys.getdefaultencoding().
 |  errors defaults to 'strict'.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __format__(self, format_spec, /)
 |      Return a formatted version of the string as described by format_spec.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  

### Strings

In [15]:
my_string = 'thisStringIsAwsome'

In [16]:
my_string

'thisStringIsAwsome'

In [17]:
my_string * 2

'thisStringIsAwsomethisStringIsAwsome'

In [18]:
my_string + 'AnotherString'

'thisStringIsAwsomeAnotherString'

In [19]:
'Is' in my_string

True

In [20]:
my_string[3]

's'

In [21]:
my_string[4:9]

'Strin'

### String Methods

In [22]:
my_string.upper()

'THISSTRINGISAWSOME'

In [23]:
my_string.lower()

'thisstringisawsome'

In [24]:
my_string.count('w')

1

In [25]:
my_string.replace('e', 'i')

'thisStringIsAwsomi'

In [26]:
my_string = ' thisStringIsAwsomi '

In [27]:
my_string.strip()

'thisStringIsAwsomi'

### List

In [28]:
a = 'is'

In [29]:
b = 'nice'

In [30]:
my_list = ['my', 'list', a, b]

In [31]:
my_list

['my', 'list', 'is', 'nice']

In [32]:
my_list2 = [ [4,5,6,7], [3,4,5,6] ]

In [33]:
my_list2

[[4, 5, 6, 7], [3, 4, 5, 6]]

### Selecting elements

In [34]:
my_list

['my', 'list', 'is', 'nice']

In [37]:
my_list[-3]

'list'

In [38]:
my_list[1:3]

['list', 'is']

In [39]:
my_list[1:]

['list', 'is', 'nice']

In [40]:
my_list[:3]

['my', 'list', 'is']

In [41]:
my_list[:]

['my', 'list', 'is', 'nice']

In [42]:
my_list2

[[4, 5, 6, 7], [3, 4, 5, 6]]

In [44]:
my_list2[1][2]

5

### List Operations

In [45]:
my_list + my_list

['my', 'list', 'is', 'nice', 'my', 'list', 'is', 'nice']

In [46]:
my_list * 2

['my', 'list', 'is', 'nice', 'my', 'list', 'is', 'nice']

In [48]:
len(my_list2) > 1

True

### List Methods

In [49]:
my_list

['my', 'list', 'is', 'nice']

In [50]:
my_list.index(a)

2

In [51]:
my_list.count(a)

1

In [52]:
my_list.append('!')

In [53]:
my_list

['my', 'list', 'is', 'nice', '!']

In [54]:
my_list.remove('!')

In [55]:
my_list

['my', 'list', 'is', 'nice']

In [56]:
del(my_list[0:1])

In [57]:
my_list

['list', 'is', 'nice']

In [60]:
my_list.reverse()

In [61]:
my_list

['list', 'is', 'nice']

In [62]:
my_list.extend('!')

In [63]:
my_list

['list', 'is', 'nice', '!']

In [64]:
my_list.pop(-1)

'!'

In [65]:
my_list.insert(0, '!')

In [66]:
my_list

['!', 'list', 'is', 'nice']

In [68]:
my_list.sort()

In [69]:
my_list

['!', 'is', 'list', 'nice']

## NumPy

In [70]:
my_list = [1,2,3,4]

In [71]:
my_list

[1, 2, 3, 4]

In [72]:
import numpy as np

In [73]:
my_array = np.array(my_list)

In [74]:
my_array

array([1, 2, 3, 4])

In [75]:
my_2darray = np.array([ [1,2,3], [4,5,6] ])

In [76]:
my_2darray

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
my_array

array([1, 2, 3, 4])

In [78]:
my_array[1]

2

In [79]:
my_array[0:2]

array([1, 2])

In [81]:
my_2darray[:, 1]

array([2, 5])

In [82]:
my_array > 3

array([False, False, False,  True])

In [84]:
my_array * 3

array([ 3,  6,  9, 12])

In [85]:
my_array + np.array([5,6,7,8])

array([ 6,  8, 10, 12])

### numpy functions

In [87]:
my_2darray.shape

(2, 3)

In [88]:
np.insert(my_array, 1, 5)

array([1, 5, 2, 3, 4])

In [89]:
np.delete(my_array, [1])

array([1, 3, 4])

In [90]:
np.mean(my_array)

2.5

In [91]:
np.median(my_array)

2.5

In [93]:
np.std(my_array)

1.118033988749895

In [100]:
np.corrcoef([2,3], [4,5])

array([[1., 1.],
       [1., 1.]])